### PR TITLE
Fix for AMD specs loaded after Jasmine runs

### PR DESCRIPTION
**Pull request by sylvaingi**
With the current version of RequireJS ATM, 2.1.1, the AMD modules containing the specs were loaded after the call to execJasmine in jasmine.helper.js, preventing any spec to be run.

The issue was that execJasmine was in the window.load callback, where it should be in the require callback when AMD is enabled.

The fix is somewhat hacky but works with my AMD environment, while preserving non-AMD behaviour.

### CODE REVIEW

**Comment by jsoverson** [comment]
Thanks for submitting this, @sylvaingi. Would you be interested in writing a separate template that you think solves the AMD problem better? 

That way the amd flag can trigger this template and we won't have to worry about supporting both simultaneously.

**Comment by sylvaingi** [comment]
I get your point, it would be cleaner to separate amd spec loading and running from the classic way. I'll work on it soon.

**Comment by erikfried** [comment]
Im having the exact same problem, only that I am using YUI3.
Would it make sense if I submit an equivalent but YUI-flavoured fix?

**Comment by jsoverson** [comment]
This task is going to be moved into grunt-contrib-jasmine, and is in the process of being reworked to conform to those standards. 

@sylvaingi, we'll still likely need your work but I'm going to hold off on this until the contrib version drops.

@erikfried, adding more templates that address general needs will be valuable, so if YUI3 testing requires a different template, feel free to start on it. What you can expect is templates to be provided with all the files that are in the grunt configuration, so you can load them in whatever order is necessary.

**Comment by jsoverson** [comment]
For record, the new task has been created and pushed to [grunt-contrib-jasmine](https://github.com/gruntjs/grunt-contrib-jasmine)

It is not compatible with grunt 0.3.x so grunt-jasmine-runner will remain for the near future until 0.4.0 drops, but no active work will be made.

@sylvaingi, I'd love to see your thoughts on the [requirejs template](https://github.com/gruntjs/grunt-contrib-jasmine/blob/master/tasks/jasmine/templates/RequireJSRunner.tmpl) used.

**Pull request closed without merging**
